import type { Metadata } from "next";
import { Provider } from "@/components/ui/provider"
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from '@/components/theme/ThemeProvider'


export const metadata: Metadata = {
  title: "User List App",
  description: "Generated by Josua",
};

export default function RootLayout(props: { children: React.ReactNode }) {
  const { children } = props
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        data-new-gr-c-s-check-loaded="14.1261.0"
        data-gr-ext-installed=""  
      >
        <ThemeProvider>
          <Provider>{children}</Provider>
        </ThemeProvider>
      </body>
    </html>
  )
}
